In [1]:
# 考察使用numpy管理数据和不使用之间的差距
import numpy as np
my_arr=np.arange(1000000)
my_list=list(range(1000000))

#各个序列分别乘以2
%time for _ in range(10): my_arr2=my_arr*2

Wall time: 27 ms


In [2]:
%time for _ in range(10): my_list2=[x*2 for x in my_list]

Wall time: 1.11 s


# ndarray一种多维数组的对象

In [3]:
import numpy as np
data=np.random.randn(2,3)
data

array([[-1.33356059,  0.2412683 , -0.07928526],
       [ 0.96028981, -0.3677956 ,  3.55537688]])

In [4]:
data*10,data+data

(array([[-13.33560588,   2.41268302,  -0.79285263],
        [  9.60289814,  -3.67795602,  35.5537688 ]]),
 array([[-2.66712118,  0.4825366 , -0.15857053],
        [ 1.92057963, -0.7355912 ,  7.11075376]]))

In [5]:
#shape返回各维度大小的元组，返回说明数组数据类型的对象
data.shape,data.dtype

((2, 3), dtype('float64'))

In [6]:
# 创建ndarray,接受一切序列型的对象
data1=[6,7,8,0,1]
arr1=np.array(data1)
arr1

array([6, 7, 8, 0, 1])

In [7]:
#嵌套序列，转化成多维数组
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
arr2,arr2.dtype

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 dtype('int32'))

In [8]:
#通过zeros,ones,empty来创建一个没有任何具体值的数组

In [9]:
np.zeros(10),np.zeros((3,6)),np.empty((2,3,2))

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]),
 array([[[1.12143959e-311, 3.16202013e-322],
         [0.00000000e+000, 0.00000000e+000],
         [8.01097888e-307, 4.75733082e-038]],
 
        [[2.03833345e+184, 9.74854503e-072],
         [6.86740818e+169, 8.92800583e+165],
         [1.21629703e-046, 5.99385978e-038]]]))

In [10]:
# arange是内置函数range的数组版
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
#通过astype方法来明确转化一个数组的dtype
arr=np.array([1,2,3,4,5])
arr.dtype
float_arr=arr.astype(np.float64)
float_arr.dtype

dtype('float64')

# 数组的运算

In [12]:
#大小相等的数组之间的任何算术运算都会应用到元素级别
arr=np.array([[1.,2.,3.],[4.,5.,6.]])
arr,arr*arr,arr-arr

(array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([[ 1.,  4.,  9.],
        [16., 25., 36.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]))

In [13]:
1/arr,arr**0.5

(array([[1.        , 0.5       , 0.33333333],
        [0.25      , 0.2       , 0.16666667]]),
 array([[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]]))

In [14]:
data=np.random.randn(7,4)
#通过布尔型索引数组来选取数组中的元素
data[data<0]=0
data

array([[1.54005353, 1.18563754, 0.30181493, 0.        ],
       [0.        , 0.        , 0.00311275, 0.57455662],
       [0.        , 0.54717575, 0.        , 0.        ],
       [1.36027398, 0.16404693, 0.        , 0.        ],
       [1.33271357, 1.36589838, 0.        , 0.50245276],
       [0.        , 0.        , 0.        , 0.48666196],
       [0.77296959, 0.5009497 , 0.        , 0.51704963]])

In [16]:
arr=np.arange(10)
arr_slice=arr[5:8]
arr_slice

array([5, 6, 7])

In [17]:
arr_slice[1]=123456
arr

array([     0,      1,      2,      3,      4,      5, 123456,      7,
            8,      9])

# 布尔型索引

In [31]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.random.randn(7,4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [30]:
data

array([[-1.03721113, -1.81209121, -1.62278551, -0.62682214],
       [ 1.24323395,  1.10269074, -0.83120114,  0.25341532],
       [ 1.60657329,  0.22154092,  0.71515366,  1.47738383],
       [-0.04876524,  1.06216945, -0.95950486,  1.65407818],
       [-0.14557851,  0.07098798, -0.07520152,  0.30436095],
       [ 1.76678919,  0.27214948,  0.63258049,  0.06408325],
       [ 1.15638751, -0.49161717,  0.75990045,  0.55883162]])

In [32]:
data[names=='Bob']#布尔型数组的长度必须跟被索引的轴长度一致
data[names=='Bob',2:]

array([[ 0.9430542 ,  0.42105522],
       [-0.19139879,  0.71041262]])

In [33]:
cond=names=='Bob'
data[~cond]

array([[-0.88723989,  0.56446595, -1.09671241, -0.11992104],
       [-1.66334399, -0.61548656, -0.84746774,  2.67004016],
       [ 0.02895351,  2.09482902, -1.50360938,  0.93058114],
       [-0.84710247,  0.21655538, -0.12006238, -0.83068882],
       [-1.29519634, -0.43960882,  1.05174949, -0.30607187]])

In [34]:
data[data<0]=0#令所有负数为0
data

array([[0.19357806, 0.28967843, 0.9430542 , 0.42105522],
       [0.        , 0.56446595, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 2.67004016],
       [0.        , 2.04492824, 0.        , 0.71041262],
       [0.02895351, 2.09482902, 0.        , 0.93058114],
       [0.        , 0.21655538, 0.        , 0.        ],
       [0.        , 0.        , 1.05174949, 0.        ]])

# 花式索引

In [35]:
arr=np.empty((8,4))
for i in range(8):
    arr[i]=i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [36]:
arr[[4,0,2,1]]

array([[4., 4., 4., 4.],
       [0., 0., 0., 0.],
       [2., 2., 2., 2.],
       [1., 1., 1., 1.]])

In [37]:
arr[[-1,-3]]

array([[7., 7., 7., 7.],
       [5., 5., 5., 5.]])

In [39]:
arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [42]:
arr[[1,5,7,2],[0,3,1,2]],arr[[1,5,7,2]][:,[0,3,1,2]]#选取矩阵的行列子集

(array([ 4, 23, 29, 10]),
 array([[ 4,  7,  5,  6],
        [20, 23, 21, 22],
        [28, 31, 29, 30],
        [ 8, 11,  9, 10]]))

# 转置与轴对换

In [44]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [45]:
#计算矩阵内积
np.dot(arr.T,arr)

array([[2240, 2352, 2464, 2576],
       [2352, 2472, 2592, 2712],
       [2464, 2592, 2720, 2848],
       [2576, 2712, 2848, 2984]])

In [47]:
#高维数组的转置比较麻烦
arr=np.arange(16).reshape((2,2,4))
arr.transpose((1,0,2)),arr

(array([[[ 0,  1,  2,  3],
         [ 8,  9, 10, 11]],
 
        [[ 4,  5,  6,  7],
         [12, 13, 14, 15]]]),
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],
 
        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]]))