In [25]:
# 考察使用numpy管理数据和不使用之间的差距
import numpy as np
my_arr=np.arange(1000000)
my_list=list(range(1000000))

#各个序列分别乘以2
%time for _ in range(10): my_arr2=my_arr*2

Wall time: 21 ms


In [26]:
%time for _ in range(10): my_list2=[x*2 for x in my_list]

Wall time: 998 ms


# ndarray一种多维数组的对象

In [27]:
import numpy as np
data=np.random.randn(2,3)
data

array([[-0.8570639 ,  0.11519908, -0.44115691],
       [ 0.31249952, -2.2252004 , -1.2776426 ]])

In [7]:
data*10,data+data

(array([[ -2.6522083 , -18.76409274,  -4.76675958],
        [ -6.06446932,  13.58532616,  -4.00447404]]),
 array([[-0.53044166, -3.75281855, -0.95335192],
        [-1.21289386,  2.71706523, -0.80089481]]))

In [8]:
#shape返回各维度大小的元组，返回说明数组数据类型的对象
data.shape,data.dtype

((2, 3), dtype('float64'))

In [9]:
# 创建ndarray,接受一切序列型的对象
data1=[6,7,8,0,1]
arr1=np.array(data1)
arr1

array([6, 7, 8, 0, 1])

In [12]:
#嵌套序列，转化成多维数组
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
arr2,arr2.dtype

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 dtype('int32'))

In [ ]:
#通过zeros,ones,empty来创建一个没有任何具体值的数组

In [13]:
np.zeros(10),np.zeros((3,6)),np.empty((2,3,2))

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]),
 array([[[1.30832447e-311, 3.16202013e-322],
         [0.00000000e+000, 0.00000000e+000],
         [8.01097888e-307, 4.67013312e-062]],
 
        [[1.20858327e+161, 1.88865356e+185],
         [1.90099419e-052, 2.25376434e+184],
         [1.42564938e-071, 3.92588723e-033]]]))

In [14]:
# arange是内置函数range的数组版
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
#通过astype方法来明确转化一个数组的dtype
arr=np.array([1,2,3,4,5])
arr.dtype
float_arr=arr.astype(np.float64)
float_arr.dtype

dtype('float64')

# 数组的运算

In [20]:
#大小相等的数组之间的任何算术运算都会应用到元素级别
arr=np.array([[1.,2.,3.],[4.,5.,6.]])
arr,arr*arr,arr-arr

(array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([[ 1.,  4.,  9.],
        [16., 25., 36.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]))

In [21]:
1/arr,arr**0.5

(array([[1.        , 0.5       , 0.33333333],
        [0.25      , 0.2       , 0.16666667]]),
 array([[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]]))

In [24]:
data=np.random.randn(7,4)
#通过布尔型索引数组来选取数组中的元素
data[data<0]=0
data

array([[0.        , 1.31863198, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.58013655],
       [0.        , 0.34458031, 1.18025871, 0.        ],
       [0.08645577, 0.        , 0.        , 0.        ],
       [0.        , 0.32714862, 0.        , 0.48873588],
       [0.60839296, 0.99224602, 1.69002018, 0.        ],
       [1.20007999, 0.97747753, 0.        , 0.32022774]])